"""Regenerate src/connectome.js from the public Male CNS connectome (v1.0, CC-BY 4.0).

    pip install pandas pyarrow
    python scripts/extract_counts.py
"""
import json
import pathlib
import urllib.request

import pandas as pd

URL = (
    "https://storage.googleapis.com/flyem-male-cns/v1.0/connectome-data/"
    "flat-connectome/body-annotations-male-cns-v1.0-minconf-0.5.feather"
)
ROOT = pathlib.Path(__file__).resolve().parent.parent
CACHE = ROOT / "scripts" / "body-annotations-male-cns-v1.0-minconf-0.5.feather"
OUT = ROOT / "src" / "connectome.js"


def per_side(neurons, cell_type):
    counts = neurons[neurons["type"] == cell_type]["somaSide"].value_counts()
    return {"left": int(counts.get("L", 0)), "right": int(counts.get("R", 0))}


def main():
    if not CACHE.exists():
        print(f"Downloading annotations (~14 MB) to {CACHE.name}")
        urllib.request.urlretrieve(URL, CACHE)
    annotations = pd.read_feather(CACHE)
    neurons = annotations[annotations["superclass"].notna()]

    gamma_d = per_side(neurons, "KCg-d")        # visual Kenyon cells, ventral accessory calyx
    alpha_beta_p = per_side(neurons, "KCab-p")  # visual Kenyon cells, dorsal accessory calyx
    dopamine = neurons[neurons["class"] == "DAN"]["type"].astype(str)

    data = {
        "dataset": "male-cns:v1.0",
        "neurons": int(len(neurons)),
        "eyeColumns": per_side(neurons, "L2"),  # one L2 lamina cell per eye column
        "visualKenyonCells": {
            side: {"KCg-d": gamma_d[side], "KCab-p": alpha_beta_p[side]} for side in ("left", "right")
        },
        "kenyonCells": int((neurons["class"] == "Kenyon_Cell").sum()),
        "apl": per_side(neurons, "APL"),
        "dopamineNeurons": {
            "total": int(len(dopamine)),
            "PAM": int(dopamine.str.startswith("PAM").sum()),
            "PPL1": int(dopamine.str.startswith("PPL1").sum()),
        },
        "mbons": int((neurons["class"] == "MBON").sum()),
    }

    body = json.dumps(data, indent=2).replace("\n", "\n  ")
    OUT.write_text(
        "// Generated by scripts/extract_counts.py. Do not edit by hand.\n"
        "// Source: Male CNS connectome v1.0, HHMI Janelia FlyEM (CC-BY 4.0).\n"
        "(function (F) {\n"
        f"  F.CONNECTOME = {body};\n"
        "})(globalThis.FLYDO = globalThis.FLYDO || {});\n"
    )
    print(f"Wrote {OUT.relative_to(ROOT)}")
    print(json.dumps(data, indent=2))


if __name__ == "__main__":
    main()
