// Generated by scripts/extract_counts.py. Do not edit by hand.
// Source: Male CNS connectome v1.0, HHMI Janelia FlyEM (CC-BY 4.0).
(function (F) {
  F.CONNECTOME = {
    "dataset": "male-cns:v1.0",
    "neurons": 166700,
    "eyeColumns": {
      "left": 886,
      "right": 893
    },
    "visualKenyonCells": {
      "left": {
        "KCg-d": 99,
        "KCab-p": 64
      },
      "right": {
        "KCg-d": 107,
        "KCab-p": 65
      }
    },
    "kenyonCells": 4064,
    "apl": {
      "left": 1,
      "right": 1
    },
    "dopamineNeurons": {
      "total": 340,
      "PAM": 316,
      "PPL1": 16
    },
    "mbons": 97
  };
})(globalThis.FLYDO = globalThis.FLYDO || {});
